Algoritmo "ExRepetição"

Var
   numero, valor, saltar: inteiro


Inicio

      Escreva ("Digite um numero: ")
      Leia(valor)
      Escreva("De quanto em quanto você quer saltar ? ")
      Leia(saltar)
      numero <- 0
      Enquanto (numero <= valor) faca
              EscrevaL ("Negativo")
              numero <- numero + saltar
      FimEnquanto
      EscrevaL ("Chegou ao seu número")


Fimalgoritmo